server:
  port: 8082
  servlet:
    context-path: /user-service
spring:
  datasource:
    url: jdbc:mariadb://115.146.122.211:3306/authentication
    username: el-course
    password: 123456aA
    driver-class-name: org.mariadb.jdbc.Driver
